#!/usr/bin/env python

from argparse import ArgumentParser
from commands import getstatusoutput
import logging, sys
from logging import debug, error, info
from json import loads, dumps
from yaml import safe_load, YAMLError

def format(s, **kwds):
  return s % kwds

def sync():
  info("here")

if __name__ == "__main__":
  parser = ArgumentParser()
  parser.add_argument("action")
  parser.add_argument("--config", "-c", dest="configFile", default="aliCvmfsPublish.conf",
                      help="Configuration file.")
  parser.add_argument("--debug", "-d", dest="debug", action="store_true", default=False)
  args = parser.parse_args()
  
  logger = logging.getLogger()
  logger_handler = logging.StreamHandler()
  logger.addHandler(logger_handler)

  if args.debug:
    logger_handler.setFormatter(logging.Formatter('%(levelname)s: %(message)s'))
    logger.setLevel(logging.DEBUG)
  else:
    logger.setLevel(logging.INFO)

  try:
    with open(args.configFile, "r") as cf:
      conf = safe_load(cf.read())
  except (IOError, YAMLError) as e:
    error( format("While reading %(configFile)s: " + str(e), configFile=args.configFile) )
    sys.exit(1)

  debug("Configuration: "+dumps(conf, indent=2))

  if args.action == "sync":
    sync()
