#!/usr/bin/env python
# Configure envvar MESOS_DNS with a list of comma-separated Mesos masters replying on port 8123 on
# plain HTTP. Returns a single IP address resolving the single command-line parameter.
import os, sys
from random import random, choice
from requests import get
dns = os.environ.get("MESOS_DNS", "alimesos01.cern.ch,alimesos02.cern.ch,alimesos03.cern.ch").split(",")
if len(sys.argv) != 2:
    print("Usage: mesos-dns-lookup <service>.<framework>.mesos")
    sys.exit(1)
what = sys.argv[1]
for d in sorted(dns, key=lambda k: random()):
    try:
        ips = [ item["ip"] for item in get("http://%s:8123/v1/hosts/%s" % (d, what)).json() ]
        break
    except:
        ips = []
if ips:
    print(choice(ips))
else:
    print(what)
