#!/usr/bin/env python
from __future__ import print_function

import os,sys,time
from github import Github

if __name__ == "__main__":
  gh = Github(login_or_token=os.environ["GITHUB_TOKEN"])
  print("Github API used %s/%s" % gh.rate_limiting, file=sys.stderr)
