#!/usr/bin/env python
from __future__ import print_function

import os,sys,time
from github import Github

if __name__ == "__main__":
  gh = Github(login_or_token=os.environ["GITHUB_TOKEN"])
  parts = [time.time()] + [x for x in gh.rate_limiting]
  print("%s,%s,%s" % tuple(parts), file=sys.stderr)
