#!/bin/sh -ex
# Script to create a mirror of alibuild repository on 
# and S3 bucket
BUCKET=${BUCKET:-alibuild-repo}
ENDPOINT=${ENDPOINT:-s3.cern.ch}

# Helper which resolves a symbolink link and stores the file it point to in the
# associated S3 object
copy_link() {
  DST=$1
  readlink $DST | s3cmd put -s -v --host $ENDPOINT --host-bucket $BUCKET.ENDPOINT - s3://$BUCKET/$DST
}

# Helper which copies all the contexts of the specified REPO on S3.
# Notice we proceed one hash bucket at the time to provide a more
# incremental approach.
mirror_repo() {
  PREFIX=$1
  REPO=$2
  pushd $PREFIX
    find $REPO/store -mindepth 1 -maxdepth 1 -type d -print0 | xargs -n1 -0 -P16 -I{} s3cmd sync -v --host $ENDPOINT --host-bucket $BUCKET.$ENDPOINT {}/ s3://$BUCKET
    find . -type l -exec copy_link {} \;
  popd
}

mirror_repo /build/reports/repo TARS/slc7_x86-64
