---
name: Create label for new async branch or tag

'on':
  workflow_call:

permissions:
  pull-requests: write   # to create labels, see https://docs.github.com/en/rest/issues/labels?apiVersion=2022-11-28#create-a-label

jobs:
  print-labels:
    name: Print labels
    runs-on: ubuntu-latest
    # only run if the created branch or tag starts with the correct pattern, namely "async-"
    if: startsWith(github.ref, 'refs/heads/async-v') || startsWith(github.ref, 'refs/tags/async-v')
    steps:
      - name: Create async branch or tag label
        env:
          GH_TOKEN: ${{ github.token }}
          ref: ${{ github.ref }}

        id: create_label
        run: |
          # to be on the safe side, check the full ref
          case "${ref}" in
            refs/heads/*) what_am_i=branch
            ;;
            refs/tags/*) what_am_i=tag
            ;;
            *) echo "Invalid ref ${ref}, abort." && exit 1
            ;;
          esac
          # extract only the branch or tag pattern we are really interested in
          ref="${ref##*/}"
          gh label create --repo "${GITHUB_REPOSITORY}" "${ref}" --description "Concerns ${what_am_i} ${ref}" --color 95C6F0
