---
name: Create label for new async branch

# Foreseen to be used when async-v* branches are pushed in repos that include this workflow
'on':
  workflow_call:

permissions:
  pull-requests: write   # to create labels, see https://docs.github.com/en/rest/issues/labels?apiVersion=2022-11-28#create-a-label

jobs:
  print-labels:
    name: Print labels
    runs-on: ubuntu-latest
    # only run if the created branch or tag starts with the correct pattern, namely "async-v"
    # while the workflow is supposed to only run when branches like async-v* are created (to be filtered in downstream repos),
    # we add this check to make sure we don't see any surprises in case filters are forgotten or wrongly implemented
    if: startsWith(github.ref, 'refs/heads/async-v')
    steps:
      - name: Create async branch label
        env:
          GH_TOKEN: ${{ github.token }}
          ref: ${{ github.ref }}

        id: create_label
        run: |
          # to be on the safe side, check the full ref
          # extract only the branch or tag pattern we are really interested in
          ref="${ref##*/}"
          [[ "$(gh label list --repo "${GITHUB_REPOSITORY}" --json name --jq '.[] | select(.name == "${ref}")')" == "" ]] &&  gh label create --repo "${GITHUB_REPOSITORY}" "${ref}" --description "Request cherry-picks for branch ${ref}" --color 95C6F0 || true
          [[ "$(gh label list --repo "${GITHUB_REPOSITORY}" --json name --jq '.[] | select(.name == "${ref}-accepted")')" == "" ]] &&  gh label create --repo "${GITHUB_REPOSITORY}" "${ref}-accepted" --description "Request cherry-picks for branch ${ref}" --color 95C6F0 || true
